package com.example.recycleviewpeliculas

class PeliculasProvider {
    companion object {
        val peliculasList = listOf<Pelicula>(
            Pelicula("TheGoodFather", "América, años 40. Don Vito Corleone (Marlon Brando) es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York. Tiene cuatro hijos: Connie (Talia Shire), el impulsivo Sonny (James Caan), el pusilánime Fredo (John Cazale) y Michael (Al Pacino), que no quiere saber nada de los negocios de su padre. Cuando Corleone, en contra de los consejos de 'Il consigliere' Tom Hagen (Robert Duvall), se niega a participar en el negocio de las drogas, el jefe de otra banda ordena su asesinato. Empieza entonces una violenta y cruenta guerra entre las familias mafiosas","1972","https://pics.filmaffinity.com/the_godfather-488102675-large.jpg"),
            Pelicula("Planeta Tierra II", "Miniserie de TV (6 episodios). La segunda parte del mítico documental \"Planeta Tierra\", nos sumerge en increíbles paisajes y nos permite experimentar el mundo a través de la perspectiva de los animales. Viajando a través de junglas, desiertos, montañas, islas, dehesas y ciudades, esta serie documental explora las características de los habitantes más icónicos de la tierra y sus extraordinarios modos de supervivencia. La nueva tecnología nos acerca a detalles sin precedentes en la vida de los animales.","2016", "https://pics.filmaffinity.com/planet_earth_ii-875634466-large.jpg"),
            Pelicula("El padrino. Parte II","Continuación de la historia de los Corleone por medio de dos historias paralelas: la elección de Michael como jefe de los negocios familiares y los orígenes del patriarca, Don Vito Corleone, primero en su Sicilia natal y posteriormente en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.","1974","https://pics.filmaffinity.com/the_godfather_part_ii-617901053-large.jpg"),
            Pelicula("The Wire","Serie de TV (2002-2008). 5 temporadas. 60 episodios. En los barrios bajos de Baltimore, se investiga un asesinato relacionado con el mundo de las drogas. Un policía es el encargado de detener a los miembros de un importante cártel. La corrupción policial, las frágiles lealtades dentro de los cárteles y la miseria vinculada al narcotráfico son algunos de los problemas denunciados en esta serie. Parece inspirarse en series modernas como \"Los Soprano\" y en clásicos como \"Policías de Nueva York (NYPD Blue)\". El creador de la serie fue, durante años, reportero de la crónica negra de Baltimore, y uno de los coguionistas fue policía en la misma ciudad.","2002","https://pics.filmaffinity.com/the_wire-680717276-large.jpg"),
            Pelicula("Breaking Bad","Serie de TV (2008-2013). 5 temporadas. 62 episodios. Tras cumplir 50 años, Walter White (Bryan Cranston), un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. Casado con Skyler (Anna Gunn) y con un hijo discapacitado (RJ Mitte), la brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno (Aaron Paul), fabricar anfetaminas y ponerlas a la venta. Lo que pretende es liberar a su familia de problemas económicos cuando se produzca el fatal desenlace.","2008","https://pics.filmaffinity.com/breaking_bad-504442815-large.jpg"),
            Pelicula("Blue Planet II","Miniserie de TV (2017). 7 episodios. 'Blue Planet ll' se centra más en la influencia del ser humano en los océanos, la polución y el cambio climático. Esta serie incluye fragmentos jamás vistos antes en un documental.","2017", "https://pics.filmaffinity.com/blue_planet_ii-415010287-large.jpg"),
            Pelicula("Cosmos","Serie de TV (1980). 13 episodios. Tras el enorme éxito mundial de su libro \"Cosmos\", el carismático astrónomo y divulgador científico norteamericano Carl Sagan (1934-1996) lleva sus teorías y explicaciones sobre el conocimiento del Universo a la pequeña pantalla en esta aclamada serie que intenta responder a las grandes preguntas del Cosmos y la vida. Entre los temas que se abordan en los diferentes capítulos están los orígenes de la vida, la búsqueda de vida en Marte, la composición de las estrellas y las galaxias, los viajes interestelares, los efectos de la velocidad de la luz, los peligros de la destrucción de la Tierra por la tecnología humana y la búsqueda de vida extraterrestre, entre otros muchos temas","1980","https://pics.filmaffinity.com/cosmos-224838468-large.jpg"),
            Pelicula("12 Angry Men","Los doce miembros de un jurado deben juzgar a un adolescente acusado de haber matado a su padre. Todos menos uno están convencidos de la culpabilidad del acusado. El que disiente intenta con sus razonamientos introducir en el debate una duda razonable que haga recapacitar a sus compañeros para que cambien el sentido de su voto.","1957","https://pics.filmaffinity.com/12_angry_men-122099105-large.jpg"),
            Pelicula("Cosmos: A Space-Time Odyssey","Serie de TV. Más de 30 años después de que Carl Sagan buscase los límites del universo y del hombre a través de la ciencia, la nueva Cosmos propone un nuevo viaje hacia las estrellas. Presentado por el prestigioso astrofísico Neil deGrasse Tyson, esta continuación explora cómo descubrimos las leyes de la naturaleza y encontramos nuestro lugar en el tiempo y el espacio. ","2014","https://pics.filmaffinity.com/cosmos_a_space_time_odyssey-358329014-large.jpg"),
            Pelicula("Schindler's List","Oskar Schindler (Liam Neeson), un empresario alemán de gran talento para las relaciones públicas, busca ganarse la simpatía de los nazis de cara a su beneficio personal. Después de la invasión de Polonia por los alemanes en 1939, Schindler consigue, gracias a sus relaciones con los altos jerarcas nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente, gracias sobre todo a su gerente Itzhak Stern (Ben Kingsley), también judío. Pero conforme la guerra avanza, Schindler y Stern comienzan ser conscientes de que a los judíos que contratan, los salvan de una muerte casi segura en el temible campo de concentración de Plaszow, que lidera el Comandante nazi Amon Goeth (Ralph Fiennes), un hombre cruel que disfruta ejecutando judíos.","1993","https://pics.filmaffinity.com/schindler_s_list-473662617-large.jpg")
        )
    }
}